#!/bin/bash
#
# setup.sh - Smart setup script for FBS (Few-Body System) SVM code
#
# Automatically detects and configures:
# - OpenBLAS (preferred for performance)
# - Accelerate framework (macOS fallback)
# - Standard LAPACK/BLAS (Linux fallback)
#
# Usage: ./setup.sh
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
echo_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
echo_error() { echo -e "${RED}[ERROR]${NC} $1"; }
echo_section() { echo -e "\n${BLUE}=== $1 ===${NC}\n"; }

# Global variables
OPENBLAS_DIR=""
USE_OPENBLAS=false
USE_ACCELERATE=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Detect OS
detect_os() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "macos"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "linux"
    else
        echo "unknown"
    fi
}

# Detect Linux distribution
detect_linux_distro() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        echo "$ID"
    elif [ -f /etc/redhat-release ]; then
        echo "rhel"
    elif [ -f /etc/debian_version ]; then
        echo "debian"
    else
        echo "unknown"
    fi
}

# Find OpenBLAS
find_openblas() {
    echo_section "Finding OpenBLAS"

    # Check common OpenBLAS locations
    OPENBLAS_PATHS=(
        "/opt/homebrew/opt/openblas"      # macOS ARM (Homebrew)
        "/usr/local/opt/openblas"          # macOS Intel (Homebrew)
        "/usr/lib/x86_64-linux-gnu"        # Ubuntu/Debian
        "/usr/lib64"                        # RHEL/CentOS
        "/usr"
        "/usr/local"
    )

    for path in "${OPENBLAS_PATHS[@]}"; do
        if [ -f "$path/lib/libopenblas.dylib" ] || \
           [ -f "$path/lib/libopenblas.so" ] || \
           [ -f "$path/lib64/libopenblas.so" ] || \
           [ -f "$path/libopenblas.so" ]; then
            OPENBLAS_DIR="$path"
            USE_OPENBLAS=true
            echo_info "OpenBLAS found at: $OPENBLAS_DIR"
            return 0
        fi
    done

    # Check ldconfig on Linux for OpenBLAS
    if command -v ldconfig &> /dev/null; then
        if ldconfig -p 2>/dev/null | grep -q libopenblas; then
            OPENBLAS_LIB=$(ldconfig -p 2>/dev/null | grep "libopenblas.so " | head -1 | awk '{print $NF}')
            if [ -n "$OPENBLAS_LIB" ]; then
                OPENBLAS_DIR=$(dirname $(dirname "$OPENBLAS_LIB"))
                USE_OPENBLAS=true
                echo_info "OpenBLAS found via ldconfig: $OPENBLAS_DIR"
                return 0
            fi
        fi
    fi

    echo_warn "OpenBLAS not found"
    return 1
}

# Find standard LAPACK
find_lapack() {
    echo_section "Finding LAPACK/BLAS"

    # On macOS, use Accelerate framework
    if [[ "$(detect_os)" == "macos" ]]; then
        echo_info "macOS detected - Accelerate framework available"
        USE_ACCELERATE=true
        return 0
    fi

    # On Linux, check for standard LAPACK
    if command -v ldconfig &> /dev/null; then
        if ldconfig -p 2>/dev/null | grep -q "libblas\|liblapack"; then
            echo_info "Standard BLAS/LAPACK found"
            return 0
        fi
    fi

    # Check common locations
    if [ -f "/usr/lib/x86_64-linux-gnu/libblas.so" ] || \
       [ -f "/usr/lib64/libblas.so" ] || \
       [ -f "/usr/lib/libblas.so" ]; then
        echo_info "Standard BLAS/LAPACK found"
        return 0
    fi

    echo_warn "LAPACK/BLAS not found"
    return 1
}

# Generate Makefile configuration
generate_makefile() {
    echo_section "Generating Makefile Configuration"

    local MAKE_INC="${SCRIPT_DIR}/make.inc"

    # Determine library configuration
    if $USE_OPENBLAS; then
        if [[ "$(detect_os)" == "macos" ]]; then
            LAPACK_LIBS="-L${OPENBLAS_DIR}/lib -lopenblas"
        else
            if [ -d "${OPENBLAS_DIR}/lib64" ]; then
                LAPACK_LIBS="-L${OPENBLAS_DIR}/lib64 -lopenblas"
            else
                LAPACK_LIBS="-L${OPENBLAS_DIR}/lib -lopenblas"
            fi
        fi
        LAPACK_NAME="OpenBLAS"
    elif $USE_ACCELERATE; then
        LAPACK_LIBS="-framework Accelerate"
        LAPACK_NAME="Accelerate"
    else
        LAPACK_LIBS="-llapack -lblas"
        LAPACK_NAME="Standard LAPACK/BLAS"
    fi

    echo_info "Using: $LAPACK_NAME"
    echo_info "Library flags: $LAPACK_LIBS"

    # Generate make.inc
    cat > "$MAKE_INC" << EOF
#===============================================================================
# make.inc - Auto-generated by setup.sh
# Generated on: $(date)
# OS: $(detect_os)
# BLAS/LAPACK: $LAPACK_NAME
#===============================================================================

#-------------------------------------------------------------------------------
# Compiler settings
#-------------------------------------------------------------------------------
FC = gfortran
FFLAGS = -O3 -march=native -ffast-math -cpp

# Debug flags (uncomment for debugging)
# FFLAGS = -g -O0 -Wall -Wextra -fcheck=all -fbacktrace -cpp

#-------------------------------------------------------------------------------
# LAPACK/BLAS configuration
#-------------------------------------------------------------------------------
LAPACK_FLAGS = -DUSE_LAPACK
LAPACK_LIBS = $LAPACK_LIBS

#-------------------------------------------------------------------------------
# OpenBLAS specific (if found)
#-------------------------------------------------------------------------------
EOF

    if $USE_OPENBLAS; then
        cat >> "$MAKE_INC" << EOF
OPENBLAS_DIR = $OPENBLAS_DIR
USE_OPENBLAS = true
EOF
    else
        cat >> "$MAKE_INC" << EOF
OPENBLAS_DIR =
USE_OPENBLAS = false
EOF
    fi

    echo_info "make.inc generated at: $MAKE_INC"

    # Update Makefile to use make.inc
    update_makefile
}

# Update main Makefile to include make.inc
update_makefile() {
    local MAKEFILE="${SCRIPT_DIR}/Makefile"
    local MAKEFILE_BAK="${SCRIPT_DIR}/Makefile.bak"

    # Backup original Makefile
    if [ -f "$MAKEFILE" ]; then
        cp "$MAKEFILE" "$MAKEFILE_BAK"
    fi

    # Check if Makefile already includes make.inc
    if grep -q "include make.inc" "$MAKEFILE" 2>/dev/null; then
        echo_info "Makefile already configured to use make.inc"
        return
    fi

    # Create new Makefile that includes make.inc
    cat > "$MAKEFILE" << 'EOF'
#===============================================================================
# Makefile for FBS (Few-Body System) SVM Calculation
#===============================================================================
#
# This Makefile builds the modern Fortran version of the SVM code.
#
# Usage:
#   ./setup.sh        - Configure for your system (run first!)
#   make              - Build the program
#   make clean        - Remove build files
#   make help         - Show this help
#
#===============================================================================

# Include auto-generated configuration
-include make.inc

# Default values if make.inc not found
FC ?= gfortran
FFLAGS ?= -O3 -march=native -ffast-math -cpp
LAPACK_FLAGS ?= -DUSE_LAPACK

# Detect macOS and use Accelerate if LAPACK_LIBS not set
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
    LAPACK_LIBS ?= -framework Accelerate
else
    LAPACK_LIBS ?= -llapack -lblas
endif

#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
SRCDIR = src
OBJDIR = obj
BINDIR = .

#-------------------------------------------------------------------------------
# Source files (in dependency order)
#-------------------------------------------------------------------------------
SOURCES = \
    $(SRCDIR)/constants_mod.f90 \
    $(SRCDIR)/parameters_mod.f90 \
    $(SRCDIR)/random_mod.f90 \
    $(SRCDIR)/linear_algebra_mod.f90 \
    $(SRCDIR)/special_functions_mod.f90 \
    $(SRCDIR)/coordinate_transform_mod.f90 \
    $(SRCDIR)/permutation_mod.f90 \
    $(SRCDIR)/potential_mod.f90 \
    $(SRCDIR)/matrix_elements_mod.f90 \
    $(SRCDIR)/diagonalization_mod.f90 \
    $(SRCDIR)/io_mod.f90 \
    $(SRCDIR)/svm_mod.f90 \
    $(SRCDIR)/main.f90

# Object files
OBJECTS = $(patsubst $(SRCDIR)/%.f90,$(OBJDIR)/%.o,$(SOURCES))

# Executable name
PROGRAM = fbs

#-------------------------------------------------------------------------------
# Default target
#-------------------------------------------------------------------------------
.PHONY: all clean help

all: $(BINDIR)/$(PROGRAM)
	@echo ""
	@echo "Build complete: $(PROGRAM)"
	@echo "LAPACK: $(LAPACK_LIBS)"
	@echo ""

#-------------------------------------------------------------------------------
# Create object directory
#-------------------------------------------------------------------------------
$(OBJDIR):
	mkdir -p $(OBJDIR)

#-------------------------------------------------------------------------------
# Compile source files to object files
#-------------------------------------------------------------------------------
$(OBJDIR)/%.o: $(SRCDIR)/%.f90 | $(OBJDIR)
	$(FC) $(FFLAGS) $(LAPACK_FLAGS) -c $< -o $@ -J$(OBJDIR)

#-------------------------------------------------------------------------------
# Link object files to executable
#-------------------------------------------------------------------------------
$(BINDIR)/$(PROGRAM): $(OBJECTS)
	$(FC) $(FFLAGS) -o $@ $(OBJECTS) $(LAPACK_LIBS)

#-------------------------------------------------------------------------------
# Module dependencies
#-------------------------------------------------------------------------------
$(OBJDIR)/parameters_mod.o: $(OBJDIR)/constants_mod.o
$(OBJDIR)/random_mod.o: $(OBJDIR)/constants_mod.o
$(OBJDIR)/linear_algebra_mod.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o
$(OBJDIR)/special_functions_mod.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o
$(OBJDIR)/coordinate_transform_mod.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o $(OBJDIR)/linear_algebra_mod.o
$(OBJDIR)/permutation_mod.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o
$(OBJDIR)/potential_mod.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o $(OBJDIR)/special_functions_mod.o
$(OBJDIR)/matrix_elements_mod.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o $(OBJDIR)/linear_algebra_mod.o $(OBJDIR)/potential_mod.o
$(OBJDIR)/diagonalization_mod.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o $(OBJDIR)/linear_algebra_mod.o $(OBJDIR)/special_functions_mod.o
$(OBJDIR)/io_mod.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o $(OBJDIR)/special_functions_mod.o $(OBJDIR)/potential_mod.o
$(OBJDIR)/svm_mod.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o $(OBJDIR)/random_mod.o $(OBJDIR)/linear_algebra_mod.o $(OBJDIR)/coordinate_transform_mod.o $(OBJDIR)/matrix_elements_mod.o $(OBJDIR)/diagonalization_mod.o $(OBJDIR)/io_mod.o
$(OBJDIR)/main.o: $(OBJDIR)/constants_mod.o $(OBJDIR)/parameters_mod.o $(OBJDIR)/io_mod.o $(OBJDIR)/coordinate_transform_mod.o $(OBJDIR)/permutation_mod.o $(OBJDIR)/svm_mod.o

#-------------------------------------------------------------------------------
# Clean build files
#-------------------------------------------------------------------------------
clean:
	rm -rf $(OBJDIR)
	rm -f $(BINDIR)/$(PROGRAM)
	rm -f *.mod
	@echo "Clean complete"

#-------------------------------------------------------------------------------
# Help target
#-------------------------------------------------------------------------------
help:
	@echo ""
	@echo "FBS (Few-Body System) SVM Calculation"
	@echo "======================================"
	@echo ""
	@echo "Setup:"
	@echo "  ./setup.sh        - Auto-detect and configure BLAS/LAPACK"
	@echo ""
	@echo "Build:"
	@echo "  make              - Build the program"
	@echo "  make clean        - Remove build files"
	@echo "  make help         - Show this help"
	@echo ""
	@echo "Configuration:"
	@echo "  Edit make.inc to customize compiler flags"
	@echo ""
EOF

    echo_info "Makefile updated"
}

# Verify installation
verify_installation() {
    echo_section "Verifying Installation"

    local errors=0

    # Check gfortran
    if command -v gfortran &> /dev/null; then
        echo_info "gfortran: $(gfortran --version | head -1)"
    else
        echo_error "gfortran not found!"
        ((errors++))
    fi

    # Check library
    if $USE_OPENBLAS; then
        if [ -f "${OPENBLAS_DIR}/lib/libopenblas.dylib" ] || \
           [ -f "${OPENBLAS_DIR}/lib/libopenblas.so" ] || \
           [ -f "${OPENBLAS_DIR}/lib64/libopenblas.so" ]; then
            echo_info "OpenBLAS: found at ${OPENBLAS_DIR}"
        else
            echo_warn "OpenBLAS library not found at expected location"
        fi
    elif $USE_ACCELERATE; then
        echo_info "Accelerate framework: available (macOS built-in)"
    else
        echo_info "Standard LAPACK/BLAS: will be used"
    fi

    return $errors
}

# Build test
build_test() {
    echo_section "Building Program"

    cd "$SCRIPT_DIR"
    make clean 2>/dev/null || true

    if make; then
        echo_info "Build successful!"
        return 0
    else
        echo_error "Build failed!"
        return 1
    fi
}

# Run quick test
run_test() {
    echo_section "Running Quick Test"

    cd "$SCRIPT_DIR"

    if [ ! -f "./fbs" ]; then
        echo_warn "Executable not found, skipping test"
        return 1
    fi

    # Create test directory
    mkdir -p test_setup
    cp example1/fbs.inp example1/pot.inp test_setup/
    cd test_setup

    # Run with timing
    echo_info "Running example1 (3-body problem)..."

    local start_time=$(date +%s.%N)
    ../fbs 2>&1 | tail -5
    local end_time=$(date +%s.%N)

    local elapsed=$(echo "$end_time - $start_time" | bc 2>/dev/null || echo "N/A")
    echo_info "Wall time: ${elapsed} seconds"

    cd ..
    rm -rf test_setup

    return 0
}

# Print summary
print_summary() {
    echo_section "Setup Summary"

    echo "Configuration:"
    echo "  OS: $(detect_os)"
    if $USE_OPENBLAS; then
        echo "  BLAS/LAPACK: OpenBLAS ($OPENBLAS_DIR)"
    elif $USE_ACCELERATE; then
        echo "  BLAS/LAPACK: Accelerate framework (macOS)"
    else
        echo "  BLAS/LAPACK: Standard system libraries"
    fi
    echo ""

    echo "Files generated:"
    echo "  make.inc  - Compiler and library configuration"
    echo "  Makefile  - Updated build system"
    echo ""

    echo "Next steps:"
    echo "  1. Build: make"
    echo "  2. Run:   cd example1 && ../fbs"
    echo ""
}

# Main function
main() {
    echo "=========================================="
    echo "  FBS (Few-Body System) Setup Script"
    echo "=========================================="

    # Try to find OpenBLAS first
    if find_openblas; then
        echo_info "Will use OpenBLAS for best performance"
    else
        # Fall back to other options
        if find_lapack; then
            if $USE_ACCELERATE; then
                echo_info "Will use macOS Accelerate framework"
            else
                echo_info "Will use standard LAPACK/BLAS"
            fi
        else
            echo_error "No BLAS/LAPACK library found!"
            echo_error "Please install OpenBLAS:"
            echo_error "  macOS: brew install openblas"
            echo_error "  Ubuntu: sudo apt install libopenblas-dev"
            exit 1
        fi
    fi

    # Generate configuration
    generate_makefile

    # Verify
    verify_installation || echo_warn "Some verification checks failed"

    # Build
    build_test || exit 1

    # Quick test
    run_test || true

    # Summary
    print_summary

    echo "=========================================="
    echo_info "Setup complete!"
    echo "=========================================="
}

# Run main function
main "$@"
